#!/usr/bin/env sh



sudo apt install -y             \
  acpi                          \
  automake                      \
  bat                           \
  blueman                       \
  brightnessctl                 \
  btop                          \
  compton                       \
  curl                          \
  dbus-bin                      \
  dbus-x11                      \
  dconf-editor                  \
  dunst                         \
  ffmpeg                        \
  git                           \
  git-delta                     \
  gitk                          \
  glow                          \
  htop                          \
  kitty                         \
  lxappearance                  \
  maim                          \
  make                          \
  mc                            \
  meld                          \
  mpv                           \
  ncdu                          \
  neofetch                      \
  network-manager               \
  network-manager-gnome         \
  nnn                           \
  notify-osd                    \
  pamixer                       \
  pavucontrol                   \
  pcmanfm                       \
  redshift                      \
  redshift-gtk                  \
  rofi                          \
  system-config-printer         \
  sxhkd                         \
  ueberzug                      \
  vorbis-tools                  \
  xbacklight                    \
  xdotool                       \
  xinput                        \
  xorg                          \
  zathura                       \
  zsh


