#!/usr/bin/env sh


sudo apt install                \
  apt-file                      \
  exuberant-ctags               \
  firefox-esr                   \
  gthumb                        \
  hsetroot                      \
  screenkey                     \
  silversearcher-ag             \
  xserver-xorg-input-synaptics
