#!/usr/bin/env sh


sudo apt install -y             \
  apt-file                      \
  cups                          \
  exuberant-ctags               \
  firefox-esr                   \
  gthumb                        \
  hsetroot                      \
  lsd                           \
  policykit-1-gnome             \
  screenkey                     \
  silversearcher-ag             \
  ueberzug                      \
  xserver-xorg-input-synaptics

# update the apt-file database
sudo apt-file update
