#!/usr/bin/env bash

VERSION="v0.10.2"
DEST_DIR="/usr/local/bin"

# don't use nightly because it contains breaking changes
#VERSION="nightly"

# Neovim - nightly
mkdir -p ~/Downloads
cd ~/Downloads
rm nvim.appimage
wget https://github.com/neovim/neovim/releases/download/$VERSION/nvim.appimage
chmod +x nvim.appimage
sudo rm $DEST_DIR/nvim
sudo cp nvim.appimage $DEST_DIR/nvim

sudo apt install fuse libfuse2


