#!/usr/bin/env bash

# kitty has this annoying habit of automatically pulling bold/italic fonts
# from the system. there is no way to disable this behavior, so the only way 
# to prevent it is not to have bold/italic fonts installed.
#
# Therefore, this script will download the .zip files with the fonts, however
# will then cherry-pick and install only "Regular" versions of the fonts.

NERD_FONTS_VERSION="v3.3.0"
NERD_FONTS_BASE_URL="https://github.com/ryanoasis/nerd-fonts/releases/download/$NERD_FONTS_VERSION"

# $1: font zip file
# $2: font file to install
function install_font() {
  if [ ! -f "$1" ]; then
    wget "$NERD_FONTS_BASE_URL/$1"
  fi

  if [ ! -f "$1" ]; then
    echo "Failed to download $1"
    return
  fi

  unzip -o $1 $2 -d ~/.fonts
}


# make sure ~/.fonts exists
mkdir ~/.fonts

# download the fonts into a temporary directory
mkdir -p ~/Downloads/fonts
cd ~/Downloads/fonts

# NOTE: On font families
# From Nerd Fonts README.md:
#   * If you are limited to monospaced fonts (because of your terminal, etc) then pick a font with `Nerd Font Mono` (or `NFM`).
#   * If you want to have bigger icons (usually around 1.5 normal letters wide) pick a font without `Mono` i.e. `Nerd Font` (or `NF`). Most terminals support this, but ymmv.
#   * If you work in a proportional context (GUI elements or edit a presentation etc) pick a font with `Nerd Font Propo` (or `NFP`).
#
# NOTE: (from myself):
#   Proportional fonts are variable-width fonts.
#   Most terminals aren't supposed to support them (Kitty doesn't, for example)
#   Not sure why are they bundled with (and named) Mono - maybe so the rest of GUI can look consistent
#   Proportional fonts (NFP) have large icons just like NF fonts do, however they do adjust the width of characters accordingly
#   This means that NF characters will take less horizontal space than NFP fonts
#   However, using NF fonts might result in some wide icons overlapping with the text that follows them
#   And this is not the case with Proportional fonts
#   So far, the best options that I have found are:
#     * For terminals, use just NF - because they have larger icons, and they are still Mono fonts
#     * For dwm, use Proportional (NFP) fonts - because there won't be any troubles with "overlapping" icons
#
# TODO: we can, probably, safely remove NFM versions from here, because we use only NF and sometimes NFP


# NOTE: we can use wildcards here, e.g. "*-Regular.?tf"

install_font CascadiaCode.zip CaskaydiaCoveNerdFont-Regular.ttf
install_font CascadiaCode.zip CaskaydiaCoveNerdFontMono-Regular.ttf
install_font CascadiaCode.zip CaskaydiaCoveNerdFontPropo-Regular.ttf

install_font FantasqueSansMono.zip FantasqueSansMNerdFont-Regular.ttf
install_font FantasqueSansMono.zip FantasqueSansMNerdFontMono-Regular.ttf
install_font FantasqueSansMono.zip FantasqueSansMNerdFontPropo-Regular.ttf

install_font IosevkaTermSlab.zip "*-Regular.?tf"

install_font OpenDyslexic.zip OpenDyslexicMNerdFont-Regular.otf
install_font OpenDyslexic.zip OpenDyslexicMNerdFontMono-Regular.otf
install_font OpenDyslexic.zip OpenDyslexicMNerdFontPropo-Regular.otf

install_font Recursive.zip RecMonoCasualNerdFont-Regular.ttf
install_font Recursive.zip RecMonoCasualNerdFontMono-Regular.ttf
install_font Recursive.zip RecMonoCasualNerdFontPropo-Regular.ttf
install_font Recursive.zip RecMonoSmCasualNerdFontMono-Regular.ttf

install_font ShareTechMono.zip ShureTechMonoNerdFont-Regular.ttf
install_font ShareTechMono.zip ShureTechMonoNerdFontMono-Regular.ttf
install_font ShareTechMono.zip ShureTechMonoNerdFontPropo-Regular.ttf

install_font Terminus.zip TerminessNerdFont-Regular.ttf
install_font Terminus.zip TerminessNerdFontMono-Regular.ttf
install_font Terminus.zip TerminessNerdFontPropo-Regular.ttf


# fonts are downloaded and unpacked; make them available to the system
cd ~/.fonts
fc-cache -fv .
