#!/usr/bin/env bash
# dwm cheatsheet: http://ratfactor.com/slackware/dwm/

# for now
DISTRO="Debian"

### dependencies
[ "$DISTRO" = "Debian" ] && sudo apt install -y gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Ubuntu" ] && sudo apt install gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Fedora" ] && sudo dnf install gcc make libXinerama-devel libXft-devel perl-open


### dwm
mkdir -p ~/src
cd ~/src/
git clone git@github.com:EY3G0R3/dwm.git
cd dwm

# set up a remote pointing to dwm on suckless.org
git remote add suckless git://git.suckless.org/dwm

make
sudo make install


### install dwm as default session manager
sudo update-alternatives --install /usr/bin/x-session-manager x-session-manager /usr/local/bin/dwm 30
sudo update-alternatives --set x-session-manager /usr/local/bin/dwm
### you can double-check it manually with any of the:
# update-alternatives --display x-session-manager
# update-alternatives --query x-session-manager
# sudo update-alternatives --config x-session-manager


### create a launcher for dwm with debug log enabled
sudo mkdir -p /usr/local/bin/
sudo cp -f ~/src/instagor/root_config/usr/local/bin/dwm-with-debug-log /usr/local/bin/


### create an xsession entry for dwm
sudo mkdir -p /usr/share/xsessions/
sudo cp -f ~/src/instagor/root_config/usr/share/xsessions/dwm.desktop /usr/share/xsessions/
sudo chmod 544 /usr/share/xsessions/dwm.desktop


### create an xsession entry for dwm with debug log enabled
sudo mkdir -p /usr/share/xsessions/
sudo cp -f ~/src/instagor/root_config/usr/share/xsessions/dwm-with-debug-log.desktop /usr/share/xsessions/
sudo chmod 544 /usr/share/xsessions/dwm-with-debug-log.desktop
