#!/usr/bin/env bash

# for now
DISTRO="Debian"

### dependencies
[ "$DISTRO" = "Debian" ] && sudo apt install -y gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Ubuntu" ] && sudo apt install gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Fedora" ] && sudo dnf install gcc make libXinerama-devel libXft-devel perl-open

### slock
sudo apt install libxrandr-dev libimlib2-dev
mkdir -p ~/src
cd ~/src/
git clone git@github.com:EY3G0R3/slock.git
cd slock
make
sudo make install

