#!/usr/bin/env bash

# for now
DISTRO="Debian"

### dependencies
[ "$DISTRO" = "Debian" ] && sudo apt install --yes gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Ubuntu" ] && sudo apt install --yes gcc make libxinerama-dev libxft-dev
[ "$DISTRO" = "Fedora" ] && sudo dnf install --yes gcc make libXinerama-devel libXft-devel perl-open


### slstatus
cd ~/src
git clone git@github.com:EY3G0R3/slstatus.git
cd slstatus


# set up a remote pointing to suckless.org
git remote add suckless git://git.suckless.org/slstatus

make
sudo make install
