#!/usr/bin/env bash

# All instructions: https://tailscale.com/download/linux/debian-sid

# CAUTION: these vary based on the distro
# The following is for Debian 13 (Trixie)
curl -fsSL https://pkgs.tailscale.com/stable/debian/sid.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
curl -fsSL https://pkgs.tailscale.com/stable/debian/sid.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list

# tailscale
sudo apt update
sudo apt install -y tailscale systemd-resolved network-manager


# need to run this command to get the tailscale IP:
# sudo tailscale up
